version: "3"
services:
  node:
    build: .
    container_name: yt-dlp-flask
    ports:
      - "8080:8000"
    volumes:
      - /mnt/d/H/Downloads/:/Downloads # 下载目录
      - /mnt/d/H/Documents/firefox_profile/:/firefox:ro # 浏览器目录

    restart: always
    # command: |
    #   cd /yt-dlp-flask
    #   gunicorn -w 10 -b 0.0.0.0:5000 app:app
