version: "3"
services:
  node:
    build: .
    container_name: yt-dlp-flask
    ports:
      - "8080:8000"
    # volumes:
    #   - /usr/anyesu/docker/tomcat-logs:/downloads
    restart: always
    # command: |
    #   cd /yt-dlp-flask
    #   gunicorn -w 10 -b 0.0.0.0:5000 app:app
